# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 13:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0002_auto_20161122_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('link', models.TextField()),
                ('category', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=3)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('location', django.contrib.gis.db.models.fields.PointField(default='POINT(0.0 0.0)', geography=True, srid=4326)),
            ],
        ),
    ]
