# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0002_auto_20161122_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
