# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 08:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_fsm'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsm',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fsm',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fsm',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='fsm',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
